version: '3.8'

# TODO obviously change user / password as this continues and make some sort 
# of way for A user to set this manually to their own preferences
services:
  database:
    image: postgres:14-alpine
    container_name: coffee-roasting-database
    environment:
      POSTGRES_DB: coffee-roasting
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: coffee-roasting-api
    container_name: coffee-roasting-api
    build:
      context: ./app/backend
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/usr/src/backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      PYTHONPATH: /usr/src/backend
      DATABASE_URL: postgres://user:password@coffee-roasting:5432/coffee-roasting
  # frontend:
  #   container_name: coffee-roasting-frontend
  #   build:
  #     context: ./frontend # Build context is the frontend directory
  #     dockerfile: Dockerfile # Assumes the Dockerfile is named Dockerfile inside the frontend folder
  #   ports:
  #     - "3000:80" # Map host port 3000 to container's Nginx port 80
  #   volumes:
  #     - ./frontend:/usr/src/app # Volume mount for development (optional for prod)
  #   environment:
  #     # This is crucial for React to know where the API is located
  #     # It should point to the host/port used by the API service.
  #     REACT_APP_API_URL: http://localhost:8000 # Use 8000 for local browser access
  #   depends_on:
  #     - api # Ensure the API is running before starting the frontend server (optional, but helpful)
volumes:
  postgres_data:
